version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_server
    environment:
      POSTGRES_DB: PD_Incidents
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/crimes.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
